- job: Peer reviewer
  organization: Milcom Conference on Military Communications
  date: 2009

- job: Peer reviewer
  organization: Conference on Collaborative Technologies and Systems
  date: 2005-2009

- job: Co-registration chair
  organization: Conference on Collaborative Technologies and Systems
  date: 2006
