- job: Peer Reviewer 
  organization: ESWC Poster and Demo Track 
  date: 2019
  type: professional

- job: Peer Reviewer 
  organization: Journal of Web Semantics 
  date: 2018
  type: professional

- job: Peer Reviewer 
  organization: International Semantic Web Conference (ISWC) 
  date: 2018
  type: professional

- job: Organizing Committee Member
  organization: Ontology Matching workshop at ISWC
  date: 2018
  type: professional

- job: Speaker 
  organization: Greater Miami Valley Computer Science Circle 
  date: 2018
  type: community

- job: Speaker 
  organization: Institute for Learning in Retirement at Miami University 
  date: 2018
  type: community

- job: Peer Reviewer 
  organization: ESWC Poster and Demo Track 
  date: 2018
  type: professional

- job: Peer Reviewer 
  organization: Information Sciences 
  date: 2018
  type: professional

- job: Peer Reviewer 
  organization: Transactions on Knowledge Discovery from Data
  date: 2017
  type: professional

- job: Judge 
  organization: Wright State University ACM Programming Competition 
  date: 2017
  type: community

- job: Speaker 
  organization: Wright State University Hackathon 
  date: 2017
  type: community

- job: Dean's Faculty Fellow 
  organization: Wright State University High School Outreach Program 
  date: 2017
  type: community

- job: Program Committee Member
  organization: International Conference on Knowledge Capture 
  date: 2017
  type: professional

- job: Peer Reviewer 
  organization: ISWC Poster and Demo Track 
  date: 2017
  type: professional

- job: Peer Reviewer 
  organization: Journal of Biomedical Semantics 
  date: 2017
  type: professional

- job: Peer Reviewer 
  organization: Journal of Geographical Systems 
  date: 2017
  type: professional

- job: Organizing Committee Member
  organization: Society, Privacy, and the Semantic Web (PrivOn) workshop at ISWC
  date: 2017
  type: professional

- job: Organizing Committee Member
  organization: Ontology Matching workshop at ISWC
  date: 2017
  type: professional

- job: Peer Reviewer 
  organization: Semantic Web Journal 
  date: 2017
  type: professional

- job: Peer Reviewer 
  organization: International Journal on Semantic Web and Information Systems (IJSWIS) 
  date: 2017
  type: professional

- job: Program Committee Member 
  organization: Poster and Demo Track at the European Semantic Web Conference (ESWC) 
  date: 2017
  type: professional

- job: Program Committee Member
  organization: PhD Symposium at the European Semantic Web Conference (ESWC) 
  date: 2017
  type: professional

- job: Judge 
  organization: Wright State University ACM Programming Competition 
  date: 2016
  type: community

- job: Speaker 
  organization: Wright State University Hackathon 
  date: 2016
  type: community

- job: Dean's Faculty Fellow 
  organization: Wright State University High School Outreach Program 
  date: 2016
  type: community

- job: Program Committee Member
  organization: 20th International Conference on Knowledge Engineering and Knowledge Management (EKAW) 
  date: 2016
  type: professional

- job: Organizing Committee Member
  organization: Society, Privacy, and the Semantic Web (PrivOn) workshop at ISWC
  date: 2016
  type: professional

- job: Organizing Committee Member
  organization: Ontology Matching workshop at ISWC
  date: 2016
  type: professional

- job: Program Committee Member
  organization: Workshop on Ontology Design Patterns at ISWC
  date: 2016
  type: professional

- job: Program Committee Member 
  organization: International Workshop on Completing and Debugging the Semantic Web 
  date: 2016
  type: professional

- job: Program Committee Member 
  organization: 9th International Conference on Formal Ontology in Information Systems 
  date: 2016
  type: professional

- job: Peer Reviewer 
  organization: Journal of Data Semantics 
  date: 2016
  type: professional

- job: Robot Design Judge 
  organization: First Lego League Student Robotics Competition 
  date: 2015
  type: community

- job: Organizing Committee Member
  organization: Ontology Matching workshop at ISWC
  date: 2015
  type: professional

- job: Organizing Committee Member
  organization: ISWC 
  date: 2015
  type: professional

- job: Program Committee Member
  organization: ISWC In Use and Software Track 
  date: 2015
  type: professional

- job: Social Media Co-Chair
  organization: Conference on Collaborative Technologies and Systems
  date: 2015
  type: professional

- job: Program Committee Member
  organization: Twenty-Ninth AAAI Conference on Artificial Intelligence
  date: 2015
  type: professional

- job: Peer Reviewer
  organization: Journal of Computers, Environment and Urban Systems 
  date: 2014
  type: professional

- job: Program Committee Member
  organization: 19th International Conference on Knowledge Engineering and Knowledge Management 
  date: 2014
  type: professional

- job: Program Committee Member
  organization: The Ninth International Workshop on Ontology Matching (OM-2014) 
  date: 2014
  type: professional

- job: In-Use Track Review Committee Member
  organization: International Semantic Web Conference 
  date: 2014
  type: professional

- job: Peer Reviewer 
  organization: Earth Science Informatics Journal
  date: 2014
  type: professional

- job: Peer Reviewer 
  organization: European Conference on Artificial Intelligence 
  date: 2014
  type: professional

- job: Pit Helper 
  organization: Xtreme BOTS Competition 
  date: 2014
  type: community

- job: Peer Reviewer
  organization: Semantic Web Journal 
  date: 2014
  type: professional

- job: Qualification Judge
  organization: High School Trebuchet Competition
  date: 2014
  type: community

- job: Peer Reviewer 
  organization: Conference on Collaborative Technologies and Systems
  date: 2014
  type: professional

- job: Peer Reviewer 
  organization: European Semantic Web Conference
  date: 2014
  type: professional

- job: Program Committee Member
  organization: International Conference on Artificial Intelligence&#58; Methodology, Systems, Applicatons
  date: 2014
  type: professional

- job: Peer Reviewer 
  organization: Journal on Data Semantics 
  date: 2013
  type: professional

- job: In-Use Track Review Committee Member
  organization: International Semantic Web Conference 
  date: 2013
  type: professional

- job: Peer Reviewer
  organization: Formal Concept Analysis for Artificial Intelligence 
  date: 2013
  type: professional

- job: Peer Reviewer
  organization: International Workshop on Description Logics 
  date: 2012
  type: professional

- job: Peer Reviewer
  organization: World Wide Web Conference 
  date: 2013
  type: professional

- job: Peer Reviewer
  organization: AAAI Artificial Intelligence on the Web Workshop 
  date: 2012
  type: professional

- job: Peer Reviewer
  organization: Milcom Conference on Military Communications
  date: 2009
  type: professional

- job: Peer Reviewer
  organization: Conference on Collaborative Technologies and Systems
  date: 2005-2010
  type: professional

- job: Co-registration chair
  organization: Conference on Collaborative Technologies and Systems
  date: 2006
  type: professional

- job: Registration chair
  organization: Conference on Collaborative Technologies and Systems
  date: 2005
  type: professional

- job: Technical Judge 
  organization: First Lego League Student Robotics Competition 
  date: 2005-2009
  type: community

- job: President 
  organization: University of Kentucky Chapter of the Association for Computing Machinery (ACM) 
  date: 2000-2001
  type: community

- job: Organizer
  organization: ACM high school programming competition 
  date: 2000
  type: community
